language: python

sudo: required

services:
  - docker

python:
  - "2.7"
  
env:
  - INSTALL="Y"
  - INSTALL="N"

branches:
  only:
    - taurus4-preview

before_install:
  # run cpascual/taurus-test docker container (Debian8 with taurus-deps and xvfb installed)
  - docker pull cpascual/taurus-test
  - if [ $INSTALL == "Y" ]; then docker run -d --name=taurus-test -e HOSTNAME=taurus-test --volume=`pwd`:/taurus cpascual/taurus-test; fi
  - if [ $INSTALL == "N" ]; then docker run -d --name=taurus-test -e HOSTNAME=taurus-test -e PYTHONPATH=/taurus/lib -e PATH=/taurus/scripts:$PATH --volume=`pwd`:/taurus cpascual/taurus-test; fi
  - sleep 10
  
script:
  - if [ $INSTALL == "Y" ]; then docker exec taurus-test python /taurus/setup.py install; fi
  - if [ $INSTALL == "N" ]; then docker exec taurus-test python /taurus/setup.py build_resources; fi
  - docker exec -ti taurus-test python /taurus/lib/taurus/test/testsuite.py
