language: python

sudo: required

services:
  - docker

python:
  - "2.7"

branches:
  only:
    - support-3.x

before_install:
  # run cpascual/taurus-test docker container (Debian8 with taurus-deps and xvfb installed)
  - docker pull cpascual/taurus-test
  - docker run -d --name=taurus-test -h taurus-test --volume=`pwd`:/taurus cpascual/taurus-test
  - sleep 10

script:
  # testsuite in 3.x is not ready for CI, so we just check that it installs without errors
  - docker exec taurus-test /bin/bash -c "cd taurus ; python setup.py install"